### ISSUE TITLE
Freelancer Jobs page shows error

### ISSUE THREAD

**Issue by PawanMeh** [erpnext/foundation#244]
1. Logon to: https://erpnext.org/erpnext-jobs

2. Traceback

Traceback (most recent call last):
  File "/home/frappe/benches/bench-2017-01-23/apps/frappe/frappe/website/render.py", line 45, in render
    data = render_page_by_language(path)
  File "/home/frappe/benches/bench-2017-01-23/apps/frappe/frappe/website/render.py", line 139, in render_page_by_language
    return render_page(path)
  File "/home/frappe/benches/bench-2017-01-23/apps/frappe/frappe/website/render.py", line 155, in render_page
    return build(path)
  File "/home/frappe/benches/bench-2017-01-23/apps/frappe/frappe/website/render.py", line 162, in build
    return build_page(path)
  File "/home/frappe/benches/bench-2017-01-23/apps/frappe/frappe/website/render.py", line 181, in build_page
    html = frappe.render_template(context.source, context)
  File "/home/frappe/benches/bench-2017-01-23/apps/frappe/frappe/utils/jinja.py", line 69, in render_template
    return get_jenv().from_string(template).render(context)
  File "/home/frappe/benches/bench-2017-01-23/env/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/frappe/benches/bench-2017-01-23/env/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/home/frappe/benches/bench-2017-01-23/apps/frappe_theme/frappe_theme/./templates/base.html", line 43, in top-level template code
    {% block content %}
  File "<template>", line 24, in block "content"
  File "/home/frappe/benches/bench-2017-01-23/env/lib/python2.7/site-packages/html2text/__init__.py", line 867, in html2text
    return h.handle(html)
  File "/home/frappe/benches/bench-2017-01-23/env/lib/python2.7/site-packages/html2text/__init__.py", line 134, in handle
    self.feed(data)
  File "/home/frappe/benches/bench-2017-01-23/env/lib/python2.7/site-packages/html2text/__init__.py", line 130, in feed
    data = data.replace("</' + 'script>", "</ignore>")
AttributeError: 'NoneType' object has no attribute 'replace'

3. Screenshot

![foundation_website_error](https://user-images.githubusercontent.com/20460498/42818591-e5276724-89ee-11e8-8b97-70af1b2f9bd4.png)

**Comment by PawanMeh** [comment]
Fixed via [commit](https://github.com/erpnext/foundation/commit/de8216a6d3f0f1860efa1179168a152203ec4ad4)
